### ISSUE TITLE
INFO - huntingcreds

### ISSUE THREAD

**Issue by GeorgePatsias** [lawrenceamer/0xsp#1]
Hello, great work on the projects!

I would like to ask how to compile the code.pas in huntingcreds since it gives me errors about imports and so on.

Thanks for your time.

**Comment by zux0x3a** [comment]
@GeorgePatsias have you used Delphi for this? better to share some screenshots. if not maybe try to create new project first on delphi and copy past the whole content of code.pas  and compile

**Comment by GeorgePatsias** [comment]
Can you please share me the compiler that you are using?

**Comment by zux0x3a** [comment]
normally i use Lazarus-ide but for this project you may download Delphi from here https://www.embarcadero.com/products/delphi/starter/free-download

**Comment by GeorgePatsias** [comment]
Thank you!
